sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester@^5.0.0
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: zLQvzdqE2F6WeICRHfph6D3Hqj+jQp50GYVer7VTzA7mhrIMBgL4ppjQTwFVv/cXudb4mdwAmrJikIjyc3HAL+hi/72hcka7ezmxF5HdV5lz1nIJ/qKxHjobqozhr3cjOkPzT7OCoFDb2ZEZtChdWbeXgkiwgujL/7HiIQK3bRLZAdYspjCRCU/wSuDGMp8LSEW7xvRtcjYqsiE3eiTuwitryzNUTcGtDv31IYNFFKP7yfEcHfYkCEWELZ2DlZo+b6MAJCiPQQ+QPBYIKmt3q9/qq1yQ6EbO4eKV5wJRtOk1BNh0twhWZ8P9Y2BFE+By8eNE7R8Y35k5flaqy/8mdI2O1xxHq8UP7N+T0MyxA5PDVN833It/OnrXMCXn76JIoVqNUp60OiM3SL+ceXiXODaT5+Uxq/LhqwTzEiBNqhKFkqOnDZ8WpNofK9BvvFivTqpUait/34TjYEAJ3TGE9xmMm0auJFwV/I/XajtOTz3XBplf8wPiATrvNhts3qLQURBmWNfYajRvPYw+RuNSbMEst9nL9tTl5P45sYg/gYgxljSXutDyjsChq8og608wHUUb6BqULOHNoNerUVBk6OTGglgzA7Yd57+9wjCtUoMY5FIZfPt7UtRhOpLY+nz+V/Yn3Jj4hTC16bvMJJXttL602NwmPZ/fXSqWwW5+y+s=
  - secure: qtHgbZwEfT0TQ8L3CjJDsdmAku4pEhSt6JVj1XO7jSC9YYoEjIqIH6W8iIY0tbnd7VrMLfBAnnWoCRL3YXKMCZ1KjQLT4ey6fh9sHa7Pi9hY6lwyzXs58bfhRCvoLyzpWciI0iLR0S/Us1jmcthS9ZR81/doKUAr1e9+A0RGqrrjHAxpqerIRV/ePhZCcBHPC1gsmmWF8hOVrJqX+Q04TnT5sx3zeJlk2cYhRiCUN7U3r4y4tOHH9WmyH+YxADitLZnAQ1oyLatav5wVJzqeVzPMu2ONmOIxOOS7+5XbE80ixhErwTAPqG4GY39n0PQbdmiDbhiKnku+PXvvVUPHgjVFhsLqpVTrgsWmMprGHSuGRQoI8MwYE4cPMxbJkD+Y19gx0CNdq6pcypPN7Ans2KV4FS8nL83VgrwU8qgQl0EOx2kOgl3RUlZZFUgrRa7EafislqHLcN7AA0Rwq5Dh2C6xxARQ9lpqVvKnnYX9GG1UZRoJtb65TuLtXVL8Z6kb1WSrN1g4bZXVlT77ftk96xdtkd38GJKIo/9ymQOlDPTRGf4ZVisXQMiGdvTCRXLLsPH3CJ7SQUSh/NLH+Qy3wkHA0h1X7HBcTkJcV7QJTX2zi9GbgvSYYsSOsPQ34LI3rUTZLhRsXLmW9eZzS9IPafZpeYgsb3n6hanfIRHuxyo=
  - secure: idJMqR+2V9ZXCTFyvnHUfE45nLDgwXwuIdPGN0IAJDp48uhNvAsFSdsySOGF8ejjWQcqkqQSO6esr7Yibd8KMNuUCauTkmr2Zi4OBHllIZDGScgaN+Ks7vC56l55KBgZ2cshG5RD8U39yJ2QMx77xqx+vslrwGCSN49yf/4kPOs9sJZW4jcHA4geqz+mEbj2RYm9EhgSR2T3W5KyDtsjx15ujxZQ4NBAFBy2iDrgVOU1LqKHrtS/v8nE4rW1zyShsqcvEcmW/bzynpm7sMPfLH7tOhD/ZaYMwn3swgWQ6c4ArhjRL55Mi/gXCCnccOU3L5owszK9ClNUqJPaALdas4vYk5YIRvxy8cQ7SKlFlncOiGr3SQwCtnzcERCQWP/vQnO/rNxI5A0QcUVTUoyYkPVmFPnL/9uuNZFAAlilcqgyeblT/Aqbv178hj+Q8eU4MJ5DxkY81wNqOCxmqEl+s+gDxscLavsTDo37SKatgxEPCNcxqy9bpWpjBi/6E+S5sc+y7oL2DjqTnhwDN9RnVg06ynErhtHC9RDqgsnjwMIAFTEXeP+BkJXjpIwDrRpwPm0iyTfQ52JLNRHoOSSQfFM8gg6pjw0KjFWDaLXRG0CAKDKOghpfeaigTx4rPUshENs0XfuB6F+wOvRDqBsgHBH6m/dLX+4A+2iMDch99gA=
